undo_backspace: false
backspace_limit: 10
fast_inject: false

matches: 

  - trigger: "/date "
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: "/shell "
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell!"

