undo_backspace: false

matches: 

  - trigger: "/date "
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: "/shell "
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell!"

  - trigger: ":excfg"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo vim $HOME/Library/Preferences/espanso/default.yml"
